#!/usr/bin/env ruby

require 'polkastarter-lottery'
require 'csv'

file_path = 'applications.csv'

if ARGV.nil? || ARGV.size != 3
  puts "Usage:"
  puts " 1. Download '#{file_path}' from polkastarter.com, containing the structure per row: identifier,pols_power"
  puts " 2. Place the '#{file_path}' file in the root of this folder"
  puts " 3. Run ./verify <max_winners> <identifier> <seed>"
else
  begin
    file = File.open file_path
  rescue Errno::ENOENT
    puts "File '#{file_path}' does not exist. Please place it in the root directory before running"
    return
  end

  max_winners    = ARGV[0].to_i
  identifier     = ARGV[1]
  seed           = ARGV[2].to_i
  balances       = CSV.read('applications.csv', headers: true).inject({}) do |hash, row|
    hash[row['identifier']] = row['balance'].to_f
    hash
  end

  service = LotteryService.new(balances: balances, max_winners: max_winners, seed: seed)
  service.run

  winner      = service.winners.find      { |participant| participant.identifier == ARGV[1] }
  participant = service.participants.find { |participant| participant.identifier == ARGV[1] }

  # puts ""
  # puts "Winners list"
  # puts service.winners.map { |winner| "#{winner.address} | #{winner.probability} | #{winner.balance}" }
  # puts ""

  if participant.nil?
    puts "Application #{identifier} is not a participant (not applied or not eligible)"
  elsif winner
    puts "Application #{identifier} is a Winner :)"
  else
    puts "Application #{identifier} is Unlucky :("
  end
end
